apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: openshift-sandboxed-containers-azure
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: peer-pods-secret
    namespace: openshift-sandboxed-containers-operator # move to openshift-cloud-credential-operator ns
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    roleBindings: # limit
      - role: Contributor
