apiVersion: v1
kind: Pod
metadata:
  name: sleep
  annotations:
    io.containerd.cri.runtime-handler: kata-remote
      #cdi.k8s.io/devices: nvidia.com/gpu=all
spec:
  runtimeClassName: kata-remote
  containers:
    - name: sleeping
      image: nvcr.io/nvidia/cuda:12.2.2-devel-ubi9
      command: ["sleep"]
      args: ["infinity"]
      resources:
        requests:
          "nvidia.com/gpu": 1

