apiVersion: v1
kind: Pod
metadata:
  name: sleep
  annotations:
    #io.katacontainers.config.hypervisor.default_gpus: "1"
    io.containerd.cri.runtime-handler: kata-remote
spec:
  runtimeClassName: kata-remote
  containers:
    - name: sleeping
      image: fedora
      command: ["sleep"]
      args: ["infinity"]
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1001
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
